/**
 * Seed file for Tenant Management Enhancement menus
 * This file adds menus for:
 * - SMS Management (Channel, Template, Log)
 * - Notify Management (Template, Message)
 * - Tenant Enhancement (Dashboard, Quota, Audit)
 */

import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

// Menu IDs start from 2000 to avoid conflicts with existing menus
const MENU_IDS = {
  // SMS Management Parent Menu
  SMS_MANAGEMENT: 2000,
  SMS_CHANNEL: 2001,
  SMS_TEMPLATE: 2002,
  SMS_LOG: 2003,
  // SMS Button Permissions
  SMS_CHANNEL_QUERY: 2010,
  SMS_CHANNEL_ADD: 2011,
  SMS_CHANNEL_EDIT: 2012,
  SMS_CHANNEL_DELETE: 2013,
  SMS_TEMPLATE_QUERY: 2020,
  SMS_TEMPLATE_ADD: 2021,
  SMS_TEMPLATE_EDIT: 2022,
  SMS_TEMPLATE_DELETE: 2023,
  SMS_LOG_QUERY: 2030,
  SMS_LOG_DELETE: 2031,

  // Notify Management Parent Menu
  NOTIFY_MANAGEMENT: 2100,
  NOTIFY_TEMPLATE: 2101,
  NOTIFY_MESSAGE: 2102,
  // Notify Button Permissions
  NOTIFY_TEMPLATE_QUERY: 2110,
  NOTIFY_TEMPLATE_ADD: 2111,
  NOTIFY_TEMPLATE_EDIT: 2112,
  NOTIFY_TEMPLATE_DELETE: 2113,
  NOTIFY_MESSAGE_QUERY: 2120,
  NOTIFY_MESSAGE_SEND: 2121,
  NOTIFY_MESSAGE_DELETE: 2122,

  // Tenant Enhancement Parent Menu
  TENANT_ENHANCEMENT: 2200,
  TENANT_DASHBOARD: 2201,
  TENANT_QUOTA: 2202,
  TENANT_AUDIT: 2203,
  // Tenant Enhancement Button Permissions
  TENANT_DASHBOARD_VIEW: 2210,
  TENANT_QUOTA_QUERY: 2220,
  TENANT_QUOTA_EDIT: 2221,
  TENANT_AUDIT_QUERY: 2230,
  TENANT_AUDIT_EXPORT: 2231,
};

const now = new Date();

export async function seedTenantManagementEnhancementMenus() {
  console.log('Seeding Tenant Management Enhancement menus...');

  const menus = [
    // ==================== SMS Management ====================
    {
      menuId: MENU_IDS.SMS_MANAGEMENT,
      tenantId: '000000',
      menuName: '短信管理',
      parentId: 1, // Under System Management
      orderNum: 12,
      path: 'sms',
      component: '',
      query: '',
      isFrame: '1',
      isCache: '0',
      menuType: 'M',
      visible: '0',
      status: '0',
      perms: '',
      icon: 'message',
      createBy: 'admin',
      createTime: now,
      updateBy: '',
      updateTime: null,
      remark: '短信管理目录',
      delFlag: '0',
    },
    {
      menuId: MENU_IDS.SMS_CHANNEL,
      tenantId: '000000',
      menuName: '短信渠道',
      parentId: MENU_IDS.SMS_MANAGEMENT,
      orderNum: 1,
      path: 'sms-channel',
      component: 'system/sms/channel/index',
      query: '',
      isFrame: '1',
      isCache: '0',
      menuType: 'C',
      visible: '0',
      status: '0',
      perms: 'system:sms:channel:list',
      icon: 'phone',
      createBy: 'admin',
      createTime: now,
      updateBy: '',
      updateTime: null,
      remark: '短信渠道菜单',
      delFlag: '0',
    },
    {
      menuId: MENU_IDS.SMS_TEMPLATE,
      tenantId: '000000',
      menuName: '短信模板',
      parentId: MENU_IDS.SMS_MANAGEMENT,
      orderNum: 2,
      path: 'sms-template',
      component: 'system/sms/template/index',
      query: '',
      isFrame: '1',
      isCache: '0',
      menuType: 'C',
      visible: '0',
      status: '0',
      perms: 'system:sms:template:list',
      icon: 'documentation',
      createBy: 'admin',
      createTime: now,
      updateBy: '',
      updateTime: null,
      remark: '短信模板菜单',
      delFlag: '0',
    },
    {
      menuId: MENU_IDS.SMS_LOG,
      tenantId: '000000',
      menuName: '短信日志',
      parentId: MENU_IDS.SMS_MANAGEMENT,
      orderNum: 3,
      path: 'sms-log',
      component: 'system/sms/log/index',
      query: '',
      isFrame: '1',
      isCache: '0',
      menuType: 'C',
      visible: '0',
      status: '0',
      perms: 'system:sms:log:list',
      icon: 'log',
      createBy: 'admin',
      createTime: now,
      updateBy: '',
      updateTime: null,
      remark: '短信日志菜单',
      delFlag: '0',
    },
    // SMS Channel Button Permissions
    {
      menuId: MENU_IDS.SMS_CHANNEL_QUERY,
      tenantId: '000000',
      menuName: '短信渠道查询',
      parentId: MENU_IDS.SMS_CHANNEL,
      orderNum: 1,
      path: '',
      component: '',
      query: '',
      isFrame: '1',
      isCache: '0',
      menuType: 'F',
      visible: '0',
      status: '0',
      perms: 'system:sms:channel:query',
      icon: '#',
      createBy: 'admin',
      createTime: now,
      updateBy: '',
      updateTime: null,
      remark: '',
      delFlag: '0',
    },
    {
      menuId: MENU_IDS.SMS_CHANNEL_ADD,
      tenantId: '000000',
      menuName: '短信渠道新增',
      parentId: MENU_IDS.SMS_CHANNEL,
      orderNum: 2,
      path: '',
      component: '',
      query: '',
      isFrame: '1',
      isCache: '0',
      menuType: 'F',
      visible: '0',
      status: '0',
      perms: 'system:sms:channel:add',
      icon: '#',
      createBy: 'admin',
      createTime: now,
      updateBy: '',
      updateTime: null,
      remark: '',
      delFlag: '0',
    },
    {
      menuId: MENU_IDS.SMS_CHANNEL_EDIT,
      tenantId: '000000',
      menuName: '短信渠道修改',
      parentId: MENU_IDS.SMS_CHANNEL,
      orderNum: 3,
      path: '',
      component: '',
      query: '',
      isFrame: '1',
      isCache: '0',
      menuType: 'F',
      visible: '0',
      status: '0',
      perms: 'system:sms:channel:edit',
      icon: '#',
      createBy: 'admin',
      createTime: now,
      updateBy: '',
      updateTime: null,
      remark: '',
      delFlag: '0',
    },
    {
      menuId: MENU_IDS.SMS_CHANNEL_DELETE,
      tenantId: '000000',
      menuName: '短信渠道删除',
      parentId: MENU_IDS.SMS_CHANNEL,
      orderNum: 4,
      path: '',
      component: '',
      query: '',
      isFrame: '1',
      isCache: '0',
      menuType: 'F',
      visible: '0',
      status: '0',
      perms: 'system:sms:channel:remove',
      icon: '#',
      createBy: 'admin',
      createTime: now,
      updateBy: '',
      updateTime: null,
      remark: '',
      delFlag: '0',
    },
    // SMS Template Button Permissions
    {
      menuId: MENU_IDS.SMS_TEMPLATE_QUERY,
      tenantId: '000000',
      menuName: '短信模板查询',
      parentId: MENU_IDS.SMS_TEMPLATE,
      orderNum: 1,
      path: '',
      component: '',
      query: '',
      isFrame: '1',
      isCache: '0',
      menuType: 'F',
      visible: '0',
      status: '0',
      perms: 'system:sms:template:query',
      icon: '#',
      createBy: 'admin',
      createTime: now,
      updateBy: '',
      updateTime: null,
      remark: '',
      delFlag: '0',
    },
    {
      menuId: MENU_IDS.SMS_TEMPLATE_ADD,
      tenantId: '000000',
      menuName: '短信模板新增',
      parentId: MENU_IDS.SMS_TEMPLATE,
      orderNum: 2,
      path: '',
      component: '',
      query: '',
      isFrame: '1',
      isCache: '0',
      menuType: 'F',
      visible: '0',
      status: '0',
      perms: 'system:sms:template:add',
      icon: '#',
      createBy: 'admin',
      createTime: now,
      updateBy: '',
      updateTime: null,
      remark: '',
      delFlag: '0',
    },
    {
      menuId: MENU_IDS.SMS_TEMPLATE_EDIT,
      tenantId: '000000',
      menuName: '短信模板修改',
      parentId: MENU_IDS.SMS_TEMPLATE,
      orderNum: 3,
      path: '',
      component: '',
      query: '',
      isFrame: '1',
      isCache: '0',
      menuType: 'F',
      visible: '0',
      status: '0',
      perms: 'system:sms:template:edit',
      icon: '#',
      createBy: 'admin',
      createTime: now,
      updateBy: '',
      updateTime: null,
      remark: '',
      delFlag: '0',
    },
    {
      menuId: MENU_IDS.SMS_TEMPLATE_DELETE,
      tenantId: '000000',
      menuName: '短信模板删除',
      parentId: MENU_IDS.SMS_TEMPLATE,
      orderNum: 4,
      path: '',
      component: '',
      query: '',
      isFrame: '1',
      isCache: '0',
      menuType: 'F',
      visible: '0',
      status: '0',
      perms: 'system:sms:template:remove',
      icon: '#',
      createBy: 'admin',
      createTime: now,
      updateBy: '',
      updateTime: null,
      remark: '',
      delFlag: '0',
    },
    // SMS Log Button Permissions
    {
      menuId: MENU_IDS.SMS_LOG_QUERY,
      tenantId: '000000',
      menuName: '短信日志查询',
      parentId: MENU_IDS.SMS_LOG,
      orderNum: 1,
      path: '',
      component: '',
      query: '',
      isFrame: '1',
      isCache: '0',
      menuType: 'F',
      visible: '0',
      status: '0',
      perms: 'system:sms:log:query',
      icon: '#',
      createBy: 'admin',
      createTime: now,
      updateBy: '',
      updateTime: null,
      remark: '',
      delFlag: '0',
    },
    {
      menuId: MENU_IDS.SMS_LOG_DELETE,
      tenantId: '000000',
      menuName: '短信日志删除',
      parentId: MENU_IDS.SMS_LOG,
      orderNum: 2,
      path: '',
      component: '',
      query: '',
      isFrame: '1',
      isCache: '0',
      menuType: 'F',
      visible: '0',
      status: '0',
      perms: 'system:sms:log:remove',
      icon: '#',
      createBy: 'admin',
      createTime: now,
      updateBy: '',
      updateTime: null,
      remark: '',
      delFlag: '0',
    },

    // ==================== Notify Management ====================
    {
      menuId: MENU_IDS.NOTIFY_MANAGEMENT,
      tenantId: '000000',
      menuName: '站内信管理',
      parentId: 1, // Under System Management
      orderNum: 13,
      path: 'notify',
      component: '',
      query: '',
      isFrame: '1',
      isCache: '0',
      menuType: 'M',
      visible: '0',
      status: '0',
      perms: '',
      icon: 'email',
      createBy: 'admin',
      createTime: now,
      updateBy: '',
      updateTime: null,
      remark: '站内信管理目录',
      delFlag: '0',
    },
    {
      menuId: MENU_IDS.NOTIFY_TEMPLATE,
      tenantId: '000000',
      menuName: '站内信模板',
      parentId: MENU_IDS.NOTIFY_MANAGEMENT,
      orderNum: 1,
      path: 'notify-template',
      component: 'system/notify/template/index',
      query: '',
      isFrame: '1',
      isCache: '0',
      menuType: 'C',
      visible: '0',
      status: '0',
      perms: 'system:notify:template:list',
      icon: 'documentation',
      createBy: 'admin',
      createTime: now,
      updateBy: '',
      updateTime: null,
      remark: '站内信模板菜单',
      delFlag: '0',
    },
    {
      menuId: MENU_IDS.NOTIFY_MESSAGE,
      tenantId: '000000',
      menuName: '站内信消息',
      parentId: MENU_IDS.NOTIFY_MANAGEMENT,
      orderNum: 2,
      path: 'notify-message',
      component: 'system/notify/message/index',
      query: '',
      isFrame: '1',
      isCache: '0',
      menuType: 'C',
      visible: '0',
      status: '0',
      perms: 'system:notify:message:list',
      icon: 'message',
      createBy: 'admin',
      createTime: now,
      updateBy: '',
      updateTime: null,
      remark: '站内信消息菜单',
      delFlag: '0',
    },

    // Notify Template Button Permissions
    {
      menuId: MENU_IDS.NOTIFY_TEMPLATE_QUERY,
      tenantId: '000000',
      menuName: '站内信模板查询',
      parentId: MENU_IDS.NOTIFY_TEMPLATE,
      orderNum: 1,
      path: '',
      component: '',
      query: '',
      isFrame: '1',
      isCache: '0',
      menuType: 'F',
      visible: '0',
      status: '0',
      perms: 'system:notify:template:query',
      icon: '#',
      createBy: 'admin',
      createTime: now,
      updateBy: '',
      updateTime: null,
      remark: '',
      delFlag: '0',
    },
    {
      menuId: MENU_IDS.NOTIFY_TEMPLATE_ADD,
      tenantId: '000000',
      menuName: '站内信模板新增',
      parentId: MENU_IDS.NOTIFY_TEMPLATE,
      orderNum: 2,
      path: '',
      component: '',
      query: '',
      isFrame: '1',
      isCache: '0',
      menuType: 'F',
      visible: '0',
      status: '0',
      perms: 'system:notify:template:add',
      icon: '#',
      createBy: 'admin',
      createTime: now,
      updateBy: '',
      updateTime: null,
      remark: '',
      delFlag: '0',
    },
    {
      menuId: MENU_IDS.NOTIFY_TEMPLATE_EDIT,
      tenantId: '000000',
      menuName: '站内信模板修改',
      parentId: MENU_IDS.NOTIFY_TEMPLATE,
      orderNum: 3,
      path: '',
      component: '',
      query: '',
      isFrame: '1',
      isCache: '0',
      menuType: 'F',
      visible: '0',
      status: '0',
      perms: 'system:notify:template:edit',
      icon: '#',
      createBy: 'admin',
      createTime: now,
      updateBy: '',
      updateTime: null,
      remark: '',
      delFlag: '0',
    },
    {
      menuId: MENU_IDS.NOTIFY_TEMPLATE_DELETE,
      tenantId: '000000',
      menuName: '站内信模板删除',
      parentId: MENU_IDS.NOTIFY_TEMPLATE,
      orderNum: 4,
      path: '',
      component: '',
      query: '',
      isFrame: '1',
      isCache: '0',
      menuType: 'F',
      visible: '0',
      status: '0',
      perms: 'system:notify:template:remove',
      icon: '#',
      createBy: 'admin',
      createTime: now,
      updateBy: '',
      updateTime: null,
      remark: '',
      delFlag: '0',
    },
    // Notify Message Button Permissions
    {
      menuId: MENU_IDS.NOTIFY_MESSAGE_QUERY,
      tenantId: '000000',
      menuName: '站内信消息查询',
      parentId: MENU_IDS.NOTIFY_MESSAGE,
      orderNum: 1,
      path: '',
      component: '',
      query: '',
      isFrame: '1',
      isCache: '0',
      menuType: 'F',
      visible: '0',
      status: '0',
      perms: 'system:notify:message:query',
      icon: '#',
      createBy: 'admin',
      createTime: now,
      updateBy: '',
      updateTime: null,
      remark: '',
      delFlag: '0',
    },
    {
      menuId: MENU_IDS.NOTIFY_MESSAGE_SEND,
      tenantId: '000000',
      menuName: '站内信消息发送',
      parentId: MENU_IDS.NOTIFY_MESSAGE,
      orderNum: 2,
      path: '',
      component: '',
      query: '',
      isFrame: '1',
      isCache: '0',
      menuType: 'F',
      visible: '0',
      status: '0',
      perms: 'system:notify:message:send',
      icon: '#',
      createBy: 'admin',
      createTime: now,
      updateBy: '',
      updateTime: null,
      remark: '',
      delFlag: '0',
    },
    {
      menuId: MENU_IDS.NOTIFY_MESSAGE_DELETE,
      tenantId: '000000',
      menuName: '站内信消息删除',
      parentId: MENU_IDS.NOTIFY_MESSAGE,
      orderNum: 3,
      path: '',
      component: '',
      query: '',
      isFrame: '1',
      isCache: '0',
      menuType: 'F',
      visible: '0',
      status: '0',
      perms: 'system:notify:message:remove',
      icon: '#',
      createBy: 'admin',
      createTime: now,
      updateBy: '',
      updateTime: null,
      remark: '',
      delFlag: '0',
    },

    // ==================== Tenant Enhancement ====================
    {
      menuId: MENU_IDS.TENANT_ENHANCEMENT,
      tenantId: '000000',
      menuName: '租户增强',
      parentId: 1, // Under System Management
      orderNum: 14,
      path: 'tenant-enhance',
      component: '',
      query: '',
      isFrame: '1',
      isCache: '0',
      menuType: 'M',
      visible: '0',
      status: '0',
      perms: '',
      icon: 'peoples',
      createBy: 'admin',
      createTime: now,
      updateBy: '',
      updateTime: null,
      remark: '租户增强目录',
      delFlag: '0',
    },
    {
      menuId: MENU_IDS.TENANT_DASHBOARD,
      tenantId: '000000',
      menuName: '租户仪表盘',
      parentId: MENU_IDS.TENANT_ENHANCEMENT,
      orderNum: 1,
      path: 'tenant-dashboard',
      component: 'system/tenant-dashboard/index',
      query: '',
      isFrame: '1',
      isCache: '0',
      menuType: 'C',
      visible: '0',
      status: '0',
      perms: 'system:tenant:dashboard:list',
      icon: 'dashboard',
      createBy: 'admin',
      createTime: now,
      updateBy: '',
      updateTime: null,
      remark: '租户仪表盘菜单',
      delFlag: '0',
    },
    {
      menuId: MENU_IDS.TENANT_QUOTA,
      tenantId: '000000',
      menuName: '租户配额',
      parentId: MENU_IDS.TENANT_ENHANCEMENT,
      orderNum: 2,
      path: 'tenant-quota',
      component: 'system/tenant-quota/index',
      query: '',
      isFrame: '1',
      isCache: '0',
      menuType: 'C',
      visible: '0',
      status: '0',
      perms: 'system:tenant:quota:list',
      icon: 'chart',
      createBy: 'admin',
      createTime: now,
      updateBy: '',
      updateTime: null,
      remark: '租户配额菜单',
      delFlag: '0',
    },
    {
      menuId: MENU_IDS.TENANT_AUDIT,
      tenantId: '000000',
      menuName: '租户审计日志',
      parentId: MENU_IDS.TENANT_ENHANCEMENT,
      orderNum: 3,
      path: 'tenant-audit',
      component: 'system/tenant-audit/index',
      query: '',
      isFrame: '1',
      isCache: '0',
      menuType: 'C',
      visible: '0',
      status: '0',
      perms: 'system:tenant:audit:list',
      icon: 'log',
      createBy: 'admin',
      createTime: now,
      updateBy: '',
      updateTime: null,
      remark: '租户审计日志菜单',
      delFlag: '0',
    },
    // Tenant Dashboard Button Permissions
    {
      menuId: MENU_IDS.TENANT_DASHBOARD_VIEW,
      tenantId: '000000',
      menuName: '租户仪表盘查看',
      parentId: MENU_IDS.TENANT_DASHBOARD,
      orderNum: 1,
      path: '',
      component: '',
      query: '',
      isFrame: '1',
      isCache: '0',
      menuType: 'F',
      visible: '0',
      status: '0',
      perms: 'system:tenant:dashboard:view',
      icon: '#',
      createBy: 'admin',
      createTime: now,
      updateBy: '',
      updateTime: null,
      remark: '',
      delFlag: '0',
    },
    // Tenant Quota Button Permissions
    {
      menuId: MENU_IDS.TENANT_QUOTA_QUERY,
      tenantId: '000000',
      menuName: '租户配额查询',
      parentId: MENU_IDS.TENANT_QUOTA,
      orderNum: 1,
      path: '',
      component: '',
      query: '',
      isFrame: '1',
      isCache: '0',
      menuType: 'F',
      visible: '0',
      status: '0',
      perms: 'system:tenant:quota:query',
      icon: '#',
      createBy: 'admin',
      createTime: now,
      updateBy: '',
      updateTime: null,
      remark: '',
      delFlag: '0',
    },
    {
      menuId: MENU_IDS.TENANT_QUOTA_EDIT,
      tenantId: '000000',
      menuName: '租户配额修改',
      parentId: MENU_IDS.TENANT_QUOTA,
      orderNum: 2,
      path: '',
      component: '',
      query: '',
      isFrame: '1',
      isCache: '0',
      menuType: 'F',
      visible: '0',
      status: '0',
      perms: 'system:tenant:quota:edit',
      icon: '#',
      createBy: 'admin',
      createTime: now,
      updateBy: '',
      updateTime: null,
      remark: '',
      delFlag: '0',
    },
    // Tenant Audit Button Permissions
    {
      menuId: MENU_IDS.TENANT_AUDIT_QUERY,
      tenantId: '000000',
      menuName: '租户审计日志查询',
      parentId: MENU_IDS.TENANT_AUDIT,
      orderNum: 1,
      path: '',
      component: '',
      query: '',
      isFrame: '1',
      isCache: '0',
      menuType: 'F',
      visible: '0',
      status: '0',
      perms: 'system:tenant:audit:query',
      icon: '#',
      createBy: 'admin',
      createTime: now,
      updateBy: '',
      updateTime: null,
      remark: '',
      delFlag: '0',
    },
    {
      menuId: MENU_IDS.TENANT_AUDIT_EXPORT,
      tenantId: '000000',
      menuName: '租户审计日志导出',
      parentId: MENU_IDS.TENANT_AUDIT,
      orderNum: 2,
      path: '',
      component: '',
      query: '',
      isFrame: '1',
      isCache: '0',
      menuType: 'F',
      visible: '0',
      status: '0',
      perms: 'system:tenant:audit:export',
      icon: '#',
      createBy: 'admin',
      createTime: now,
      updateBy: '',
      updateTime: null,
      remark: '',
      delFlag: '0',
    },
  ];

  // Use upsert to avoid duplicate key errors
  for (const menu of menus) {
    await prisma.sysMenu.upsert({
      where: { menuId: menu.menuId },
      update: menu,
      create: menu,
    });
  }

  console.log(`Seeded ${menus.length} menus for Tenant Management Enhancement`);
}

// Export for use in main seed file
export { MENU_IDS };

// Run if executed directly
if (require.main === module) {
  seedTenantManagementEnhancementMenus()
    .then(() => {
      console.log('Seed completed successfully');
      process.exit(0);
    })
    .catch((error) => {
      console.error('Seed failed:', error);
      process.exit(1);
    })
    .finally(async () => {
      await prisma.$disconnect();
    });
}
